### ISSUE TITLE
Djangoのプロジェクト初期設定

### ISSUE THREAD

**Issue by sakanobu** [tyobi0913/bloblog#4]
# ToDo

## Djangoのアプリケーション作るまで
- [x] 初回のmigrate
- [x] superuser作成
- [x] templatesディレクトリ作成
  - [x] base.htmlの作成
- [x] staticディレクトリ作成
- [ ] 本番稼働の際のstaticディレクトリのドキュメントルートをconfig/urls.pyに書く
- [x] .gitignoreに.envファイルやオーソドックスな除外を書く
- [x] .envファイル作成
  - [x] SECRET_KEY
  - [ ] データベース
- [ ] settings.py
  - [ ] setting.pyのINSTALLED_APPSにpipで入れたパッケージを追加
  - [x] TEMPLATESのDIRS
  - [ ] データベース(PostgreSQL)
  - [ ] ロギング
  - [x] 言語
  - [x] タイムゾーン
  - [x] static
    - [x] STATIC_URL
    - [ ] STATICFILES_DIRS
    - [ ] STATIC_ROOT
  - [x] .envファイルを読み込みと該当項目の隠蔽
  - [ ] base.pyと本番環境と開発環境で分ける
    - [ ] settingsディレクトリと､その中に__init__.py､base.py､development.pyを作成
    - [ ] BASE_DIRが変わってしまうなら対応
    - [ ] 本番稼働ならDebugをFalseに
