### ISSUE TITLE
accountsアプリケーションの初期設定

### ISSUE THREAD

**Issue by sakanobu** [tyobi0913/bloblog#5]
# ToDo

## アプリケーション accounts
  - [ ] startapp accountsする
  - [ ] settings.pyのINSTALLED_APPSに追加
  - [ ] urls.pyは作らずに､config/urls.pyに書く?
  - [ ] models.pyでaccountsカスタムユーザー作る
    - [ ] make migrations
    - [ ] migrate
  - [ ] templates/accountsディレクトリは作らずに､ホームディレクトリのtemplatesに作って書くのか?
  - [ ] テストについて
    - [ ] tests.pyの削除
    - [ ] testディレクトリとその中に __init__.pyを作成
