### ISSUE TITLE
blogアプリケーションの初期設定

### ISSUE THREAD

**Issue by sakanobu** [tyobi0913/bloblog#6]
# ToDo

## アプリケーション blog
  - [ ] startapp blogする
  - [ ] settings.pyのINSTALLED_APPSに追加
  - [ ] urls.py作る
    - [ ] app_name忘れず
  - [ ] config/urls.pyからblog/urls.pyへとルーティングされるようにinclude
  - [ ] models.py
    - [ ] モデル作る
    - [ ] make migrations
    - [ ] migrate
    - [ ] diary/admin.pyへ
  - [ ] templates/blogディレクトリ作成
  - [ ] テストについて
    - [ ] tests.pyの削除
    - [ ] testディレクトリの作成
      - [ ] __init__.py作成
